version: '3.8'

services:
  backend:
    build:
      context: ./backend
    environment:
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      FRONTEND_URL: ${FRONTEND_URL}
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: fullstack
      POSTGRES_USER: fullstack
      POSTGRES_PASSWORD: fullstack
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
